#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

#set global path
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib

#local ip support 127.0.0.1
ifconfig lo up
ifconfig lo netmask 255.255.255.0

ifconfig eth0 192.2.1.99 netmask 255.255.255.0
route add default gw 192.2.1.1
ifconfig eth0 up